channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - pytorch=1.13.*=*cuda* # Need to specifically request cuda version
  - torchvision=0.14.*
  - pip>=23
  - pip:
      - pre-commit==3.6.*
      - jsonargparse[omegaconf,signatures]==4.27.*
      - tqdm==4.66.*
      - matplotlib==3.8.*
      - pandas==2.2.*
